const fs = require('fs');
const path = require('path');

const AUDIO_DIR = path.resolve(__dirname, '../public/assets/audio');
const AUDIO_MAP_FILE = path.resolve(__dirname, '../src/utils/audioMap.js');

async function cleanAudio() {
  if (!fs.existsSync(AUDIO_MAP_FILE)) {
    console.error(`Error: Cannot find ${AUDIO_MAP_FILE}`);
    console.error('Please run generate_audio.js first.');
    process.exit(1);
  }

  // Use dynamic import for the ES module (since package.json is commonjs, we read it manually or use await import)
  // To avoid issues with "require" of ES modules, we'll just parse the file content.
  const mapContent = fs.readFileSync(AUDIO_MAP_FILE, 'utf-8');
  let audioMap;
  try {
    const jsonStr = mapContent.replace('// Auto-generated by scripts/generate_audio.js\nexport const audioMap = ', '').replace(/;\n?$/, '');
    audioMap = JSON.parse(jsonStr);
  } catch (error) {
    console.error("Failed to parse audioMap.js:", error.message);
    process.exit(1);
  }

  const validFiles = new Set(Object.values(audioMap).map(url => path.basename(url)));

  if (!fs.existsSync(AUDIO_DIR)) {
    console.log(`Directory ${AUDIO_DIR} does not exist. Nothing to clean.`);
    return;
  }

  const existingFiles = fs.readdirSync(AUDIO_DIR).filter(file => file.endsWith('.mp3'));
  let deletedCount = 0;

  for (const file of existingFiles) {
    if (!validFiles.has(file)) {
      fs.unlinkSync(path.join(AUDIO_DIR, file));
      console.log(`Deleted orphaned file: ${file}`);
      deletedCount++;
    }
  }

  console.log(`\nCleanup complete. Deleted ${deletedCount} file(s). Kept ${validFiles.size} file(s).`);
}

cleanAudio();
